### PR TITLE
Fix for Batch 2489

### PR DESCRIPTION
**Pull request by arindamray1982**
Fix for Bean (id="jobExplorer" and class="org.springframework.batch.core.explore.support.JobExplorerFactoryBean") always use default table prefix

### CODE REVIEW

**Comment by mminella** [comment]
Can you please rebase and squash your commits?

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=409) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=409)!

**Comment by arindamray1982** [comment]
@mminella I am new to GitHub. Can you please guide me for "rebase and squash my commits"?

**Comment by benas** [comment]
Hi @arindamray1982 ,

The ["Squash commits"](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#squash-commits) section of the contributor guide might help you. You can find an example of how to do it in the "Pro Git" book [here](https://book.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing).

Hope this helps.
Mahmoud

**Comment by arindamray1982** [comment]
@benas I am not able to squash the commits. Followed these:

git rebase --interactive

and then:

pick c32f6ef Change 1
squash d71e0db Change 2
squash 31f0f5a Change 3
squash d2cb5a1 Change 4
squash d59301d Change 5

**Comment by arindamray1982** [comment]
@benas Rebased with current upstream/master but unable to squash the commits. Can you please take care of that?

**Comment by benas** [comment]
Thank you for the updates.

> Can you please take care of that?

Sure I can help if it's getting complicated for you. However, before that, please add a test as mentioned in the [contributor guide](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#submit-junit-test-cases-for-all-behavior-changes). 

I think it will be easier to create a new PR rather than rebasing those commits, so I'm closing this for now. Please open a new PR that includes changes for both production and test code.

Thank you upfront!

**Comment by arindamray1982** [comment]
@benas Thanks. I'll do so.

**Pull request closed without merging**
