### PR TITLE
Update schema-appendix.adoc to fix wrong names

### PR DESCRIPTION
**Pull request by quaff**
BATCH_EXECUTION_CONTEXT should be BATCH_JOB_EXECUTION_PARAMS
EXECUTION_ID should be JOB_EXECUTION_ID

Please check `Frequency` if it's up to date.

### CODE REVIEW

**Comment by benas** [comment]
Is this related to https://jira.spring.io/browse/BATCH-2853?

**Comment by quaff** [comment]
@benas Yes.

**Comment by benas** [comment]
ok thanks, I added a link to this PR in BATCH-2853.

**Comment by benas** [comment]
> BATCH_EXECUTION_CONTEXT should be BATCH_JOB_EXECUTION_PARAMS

This is actually not correct. `BATCH_EXECUTION_CONTEXT` has been replaced with `BATCH_STEP_EXECUTION_CONTEXT` and `BATCH_JOB_EXECUTION_CONTEXT` in https://github.com/spring-projects/spring-batch/commit/d272105479896ea543ce971fbb0298809b450df2#diff-9df3d792ac9c1d09e598d04018ee1f6eL71-L80. And based on the frequency "On commit interval, a.k.a. chunk" mentioned in the appendix, it is definitely not `BATCH_JOB_EXECUTION_PARAMS`: this table is not queried/updated at each commit interval. It is `BATCH_STEP_EXECUTION_CONTEXT` that is updated at this frequency, here is an excerpt from the [ExecutionContext](https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/domain.html#executioncontext) section:

```
They are two different ExecutionContexts. The one scoped to the Step is saved at every commit point in the Step, whereas the one scoped to the Job is saved in between every Step execution.
```

@quaff Could you please update the PR accordingly?

**Comment by quaff** [comment]
@benas `BATCH_STEP_EXECUTION_CONTEXT` and `BATCH_STEP_EXECUTION_CONTEXT` are queried by primary key, so they should be excluded from this table.

**Comment by benas** [comment]
Indeed, `BATCH_STEP_EXECUTION_CONTEXT` and `BATCH_JOB_EXECUTION_CONTEXT` are queried by primary keys (which are indexed by default), so this entry can be removed from the table. Thanks for the PR!

**Pull request merged**
