### PR TITLE
BATCH-2589 added test case for skipping within RepositoryItemReader

### PR DESCRIPTION
**Pull request by jahe**
BATCH-2589: RepositoryItemReader reads failed items over and over again

JIRA: https://jira.spring.io/browse/BATCH-2589

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jahe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=459)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=459) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jahe** [comment]
I already signed the Contributor License Agreement a week ago. Could you trigger a new check please?

**Comment by pivotal-issuemaster** [comment]
@jahe Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=459)!

**Comment by mminella** [comment]
Closing this PR based on comments in the related issue.

**Pull request closed without merging**
