### PR TITLE
Corrected the links for retry and sample

### PR DESCRIPTION
**Pull request by Ganapathi004**
The jump links for retry and sample are not correct.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Ganapathi004 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=613)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=613) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Ganapathi004 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=613)!

**Comment by benas** [comment]
Thank you for fixing these two links. However, the link to the `retry` sample is also incorrect in the `Skip Sample` section (see: `the details are quite similar to the [Retry Sample](#retry)` which should be `[Retry Sample](#retry-sample)`).

BTW, it looks like all links should be updated since the [GitHub Flavored Markdown](https://github.github.com/gfm/#links) does not support the `id:anchor` syntax.

It would be great to fix the README file of the samples module in a single PR, so can you please remove the `[]` and `(id:XXX)` from section titles and fix the link to each section in the two tables?

For example:

* Section title: `### [Trade Job](id:trade)` -> `### Trade Job`
* Link to section: `[trade](#trade)` -> `[trade](#trade-job)`

Many thanks upfront!

PS: there are also links in the text that should be updated and not only those in the table of context.

**Comment by Ganapathi004** [comment]
I am more than happy to do it. I will create a pull request
again once completed.
Ganapati Basimsetti

**Comment by Ganapathi004** [comment]
@benas Created the pull request [Pull Request 641](https://github.com/spring-projects/spring-batch/pull/641)

**Comment by benas** [comment]
Hi,

Thanks for the updates. I will close this PR and review #641 .

Kr,
Mahmoud

**Pull request closed without merging**
