### PR TITLE
BATCH-2405 rename beanRefContext.xml

### PR DESCRIPTION
**Pull request by jpraet**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jpraet Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=421) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jpraet Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=421)!

**Comment by mminella** [comment]
Based on https://jira.spring.io/browse/SPR-15154, we may be using a new mechanism for this for Spring 5.  Still in discussions.

**Comment by mminella** [comment]
Just so everyone watching things here is up to date, this is impacted by the ongoing conversation here: https://jira.spring.io/browse/SPR-15154

**Comment by mminella** [comment]
I'm closing this PR.  Based on the rework around Spring Framework 5, this mechanism was removed and it has been refactored in Spring Batch 4.  I don't feel that this is a fair change to be done in a point release for 3.0.x so to work around the issue this was to address, the recommended approach will be to migrate to Spring Batch 4.

**Pull request closed without merging**
