### PR TITLE
BATCH-2747: Job scoped steps can not be used within FlowBuilder

### PR DESCRIPTION
**Pull request by ArtyomGabeev**
Please refer for more details: https://jira.spring.io/browse/BATCH-2747

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ArtyomGabeev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=670)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=670) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ArtyomGabeev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=670)!

**Comment by mminella** [comment]
I made a comment on this issue.  Let's discuss there before merging this PR.

**Comment by ArtyomGabeev** [comment]
In general step can be annotated with @JobScope in order to have access to jobParameters.
 
@mminella , you right, it was my mistake when I mentioned StepScope in this issue, because it doesn't make sense.
But this fix is still reasonable if you want to create a JobScoped step, and pass some parameters (like chunk size for example)
 
BTW: I and original author have an issue with JobScoped step.

**Comment by alex2chen** [comment]
@Bean(EXPORT_CSV_NAME)
    public Job exportCsvJob(@Qualifier(STEP_NAME_EXPORTCSV) Step exportCsv) {
        return jobBuilders
                .get(EXPORT_CSV_NAME)
                .incrementer(new RunIdIncrementer())
                .repository(jobRepository)
                .start(initParamsStep())
                .next(takeCountStep())
                .next(exportCsv)
                .build();
    }
me too!
3.0.7.RELEASE!

**Comment by dongdongqin** [comment]
I have a way to use jobscope or stepscope for FlowBuilder.

please see the configuration below:

 /**
     * setlStatJob
     *
     * @param jobBuilderFactory
     * @param splitFlow
     * @param ichgStatTaskletMergedStep
     * @param ichgSetlStatClearStep
     * @return Job
     */
    @Bean(name = "singleInterchangeSettlementStatisticJob")
    public Job setlStatJob(
            JobBuilderFactory jobBuilderFactory,
            Flow splitFlow,
            Step ichgStatTaskletMergedStep,
            Step ichgSetlStatClearStep) {

        return jobBuilderFactory.get(JobEnum.SNGL_ICHG_SETL_STAT.getJobName())
                .incrementer(new RunIdIncrementer())
                .start(splitFlow)
                .next(ichgStatTaskletMergedStep)
                .next(ichgSetlStatClearStep)
//                .next(snglSetlStatFeedStep)
                .build()
                .build();

    }

    /**
     * parallel step
     *
     * @param financeStatFlow
     * @param nonFinanceStatFlow
     * @return Flow
     */
    @Bean
    public Flow splitFlow(Flow financeStatFlow,
                          Flow nonFinanceStatFlow) {

        return new FlowBuilder<SimpleFlow>("ichgStatFlow")
                .split(taskExecutor())
                .add(financeStatFlow, nonFinanceStatFlow)
                .build();
    }

    /**
     * finance Stat Flow
     *
     * @param snglFinclSetlStatMasterStep
     * @return Flow
     */
    @JobScope
    @Bean
    public Flow financeStatFlow(Step snglFinclSetlStatMasterStep) {

        return new FlowBuilder<SimpleFlow>("financeStatFlow")
                .start(snglFinclSetlStatMasterStep)
                .build();
    }

    /**
     * non Finance Stat Flow
     *
     * @param snglNonFinclSetlStatMasterStep
     * @return Flow
     */
    @JobScope
    @Bean
    public Flow nonFinanceStatFlow(Step snglNonFinclSetlStatMasterStep) {
        return new FlowBuilder<SimpleFlow>("nonFinanceStatFlow")
                .start(snglNonFinclSetlStatMasterStep)
                .build();
    }

    @Bean
    public SimpleAsyncTaskExecutor taskExecutor() {
        return new SimpleAsyncTaskExecutor() {
            @Override
            protected void doExecute(Runnable task) {
                //gets the jobExecution of the configuration thread
                JobExecution jobExecution = JobSynchronizationManager.getContext().getJobExecution();

                super.doExecute(task );

                super.doExecute(new Runnable() {
                    @Override
                    public void run() {
                        JobSynchronizationManager.register(jobExecution);
                        try {
                            task.run();
                        } finally {
                            JobSynchronizationManager.release();
                        }
                    }
                });
            }
        };
    }

the first:
we need to add the  public SimpleAsyncTaskExecutor taskExecutor() bean, because jobcontext is used under thread local.

the second:

do not use @jobscope under method splitFlow,  use  @JobScope under financeStatFlow and nonFinanceStatFlow.  because delay initialise bean.

**Comment by benas** [comment]
LGTM. Rebased and merged as 0c500794f6ef94d74196facd401d96210cd3a6f8. Thank you for your contribution!

**Pull request closed without merging**
