### PR TITLE
Use spring-doc-resources

### PR DESCRIPTION
**Pull request by Buzzardo**
This set of changes replaces some local files with those from spring-doc-resources. That way, when we change the doc files, we get those changes without further effort.

Huge thanks to Brian Clozel for his help.

### CODE REVIEW

**Comment by benas** [comment]
Building this PR locally fails with the following error:

```
$ ./gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mbenhassine/projects/spring-batch/build.gradle' line: 665

* What went wrong:
Could not determine the dependencies of task ':prepareAsciidocBuild'.
> Could not resolve all files for configuration ':docs'.
   > Could not find io.spring.docresources:spring-doc-resources:0.1.1-BUILD-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/mbenhassine/.m2/repository/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - file:/Users/mbenhassine/.m2/repository/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - file:/Users/mbenhassine/.m2/repository/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
       - https://repo.spring.io/libs-snapshot/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - https://repo.spring.io/libs-snapshot/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - https://repo.spring.io/libs-snapshot/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
       - https://repo.spring.io/libs-milestone/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - https://repo.spring.io/libs-milestone/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - https://repo.spring.io/libs-milestone/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
       - https://repo.spring.io/plugins-release/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - https://repo.spring.io/plugins-release/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - https://repo.spring.io/plugins-release/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
       - https://repo.maven.apache.org/maven2/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
       - https://jcenter.bintray.com/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.pom
       - https://jcenter.bintray.com/io/spring/docresources/spring-doc-resources/0.1.1-BUILD-SNAPSHOT/spring-doc-resources-0.1.1-BUILD-SNAPSHOT.zip
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
```

**Comment by Buzzardo** [comment]
Hi, Mahmoud,

I had to use mavenLocal() in the build because there's not yet a release of spring-doc-resources. As a consequence, to use this build.gradle file as it stands, you have to build spring-doc-resources locally, so that it is in your local maven repository.

However, I suggest that you not do that. Brian Clozel is about to create a release version for us, and that should be available on Monday. So, please do not do more with this PR at present, and I'll make a new commit next week that will get things to work correctly, without anyone having to build a dependency locally.

Thank you very much for catching the issue.

J

**Comment by mminella** [comment]
@Buzzardo Is there not a CI build publishing snapshots of the doc resources?  If not, can we get one?

**Comment by Buzzardo** [comment]
That's what Brian C is doing, I believe. He's also making sure that Damien doesn't have more changes to the styling.

**Comment by benas** [comment]
Hi Jay,

No worries. Let us know when the `spring-doc-resources` is released.

Best regards,
Mahmoud

**Comment by benas** [comment]
Great thanks! I [saw](https://twitter.com/bclozel/status/1072236806807138306) there is an effort to make all spring projects docs consistent with the same style. That would be awesome.

The build is passing now, however there are couple of issues:

1. The ToC on the left is gone:

screenshot 2018-12-13 at 10 59 26

It does not show up as in [boot's docs](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/documentation-overview.html#boot-documentation). We need to add a header with "Spring by Pivotal" logo BTW.

2. The toggle is now a radio button, is that intended? Moreover, it does not seem to work (in the following screenshot the snippet should be in XML)

screenshot 2018-12-13 at 11 03 58

3. There is a regression on [BATCH-2676](https://jira.spring.io/browse/BATCH-2676), the distribution's content with this PR is as follows:

```
# mbenhassine @ Mahmouds-MBP in ~/projects/spring-batch/build/distributions/reference on git:use-doc-resources o [10:57:40]
$ tree -d -L 2
.
├── build  // incorrect, not needed here
│   ├── css
│   ├── footer
│   ├── header
│   ├── images
│   ├── js
│   └── jsfiles
├── css  // incorrect, not needed here
├── html
│   ├── css
│   ├── images
│   └── js
├── js  // incorrect, not needed here
│   ├── highlight
│   └── tocbot
└── pdf
    ├── css  // incorrect, not needed here
    └── js  // incorrect, not needed here

18 directories
```

The overall new style looks nice (if we manage to make it like boot), but we need to fix the above issues for batch before merging this PR.

Kr,
Mahmoud

**Comment by Buzzardo** [comment]
I'm looking into it. I can't see how Brian makes the connection to the JS files, so it's going to take a while.

**Comment by Buzzardo** [comment]
That took a bit to figure out. It turned out to be multiple problems, as I described in the commit message.

Please test again, and thank you for your patience.

**Comment by Buzzardo** [comment]
I got the latest RELEASE version of spring-doc-resources. I also cleaned up the build a bit (by using a few includes rather than a ton excludes), and I removed some old JS libraries we no longer need. When I test locally, it all works (including the XML/Java toggle). Please test further, though. How many times have we all heard, "It works on my machine"?

**Comment by benas** [comment]
Thanks for the updates. I tested locally and found some regressions:

* The pdf file does not contain the version number in the front page
* The pdf file does not contain section numbers in the ToC
* When I generate the distribution with `./gradlew dist`, the `reference` folder contains all html files + `spring-batch-reference.pdf`. Html files and related resources must be under `reference/html` directory, and the `spring-batch-reference.pdf` under `reference/pdf`.
* Html files are generated in a `html5` directory and not in a `html` directory as currently. This breaks some links. We need to make sure the distribution contains the correct `html` directory.
* On master, all js are in a `jsfiles` directory, but in this PR js files are in two folders: `js` and `jsfiles`

**Comment by Buzzardo** [comment]
Thank you very much, Mahmoud. :)

I have attended to all of those issues. I am going to add section numbers to Spring's default document recipe. I was able to get them into the PDF and the single-page HTML. I thought they didn't make sense in the stand-alone HTML files, because each one then starts with 1, which is incongruous with the PDF and the single-page HTML (and, thus, might cause confusion).

Thanks again. :)

**Comment by benas** [comment]
Thank you Jay and Brian for all the effort you've put into this! LGTM now 👍  It's great to see batch docs consistent with other projects from the portfolio.

Rebased, squashed and merged as 145bacc34a3e2d7f127a922308c78411dac272b9.

**Comment by Buzzardo** [comment]
I'm glad we finally got it. :)

Thanks, Mahmoud. :)

**Pull request closed without merging**
