### PR TITLE
Update JdbcCursorItemReaderBuilder.java

### PR DESCRIPTION
**Pull request by ronsims2**
Fixed typo in error message.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ronsims2 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=683)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=683) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ronsims2 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=683)!

**Comment by benas** [comment]
Thank you for the PR!

Can you [update the test](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JdbcCursorItemReaderBuilderTests.java#L320) as well ?

Please update the year in the license header and add your name as `@author` in the changed files.

**Comment by benas** [comment]
Any update on this?

The `JdbcCursorItemReaderBuilderTests#testValidation` is failing with the change in this PR.

@ronsims2 Can you update the test as well?

**Comment by benas** [comment]
Rebased and merged as 39f4d71949a81efc3e21e2c326fd960e7befe089. I fixed the failing test on merge. Thank you for your PR.

**Pull request closed without merging**
