### PR TITLE
Fix incorrectly added functions.

### PR DESCRIPTION
**Pull request by CNJingo**
Correct that hashcode and equals were added in the chunk iterator class instead of in the chunk class.

This PR is related to #4314

### CODE REVIEW

**Comment by fmbenhassine** [comment]
Thank you for your PR. While testing it, I noticed there is test failure in `FaultTolerantChunkProcessorTests.testWriteRetryOnTwoExceptions`. Can you check please?

Also , please run `./mvnw spring-javaformat:apply` to fix code formatting as well.

**Comment by CNJingo** [comment]
I fixed it.

**Comment by CNJingo** [comment]
I'll fix it

**Comment by CNJingo** [comment]
This is a problem with Spring retry. 
```
    private void registerContext(RetryContext context, RetryState state) {
        if (state != null) {
            Object key = state.getKey();
            if (key != null) {
                if (context.getRetryCount() > 1 && !this.retryContextCache.containsKey(key)) {
                    throw new RetryException("Inconsistent state for failed item key: cache key has changed. Consider whether equals() or hashCode() for the key might be inconsistent, or if you need to supply a better key");
                }

                this.retryContextCache.put(key, context);
            }
        }

    }
```
In this code, the chunk class is being used as the key value in the retryContextCache.  

At the point where the error occurs, the item of class chunk has changed. Because this changes the hashcode, it goes inside the if conditional, unlike before.

That's why the error occurs in the 4th assertEquals method of testWriteRetryOnTwoExceptions().

This is because it throws a RetryException, which is not the expected error.

How can I fix this? Is changing the test code the right way to go?

**Comment by fmbenhassine** [comment]
Thank you for tracing the issue down to Spring Retry!

In Spring Batch, failed items are retried without any modification (it does not make sense to change an item before retrying it). So if the test changes the items before retrying them, then the test is incorrect and should be fixed. Do not hesitate to adapt it as needed. Let me know if you need help on this. Thank you!

**Comment by CNJingo** [comment]
Thank you for your review. I'll try to modify the test code according to your idea.

**Comment by CNJingo** [comment]
Done.

**Comment by fmbenhassine** [comment]
LGTM. Rebased and merged as bb337c6b2fad4f76b33525863d341e44adbf076a. Thank you for your contribution!

**Comment by fmbenhassine** [comment]
The test is actually correct. Your changes of the test makes it inconsistent with the test name.

This is actually deeper than I thought. The issue is not with Spring Retry. The issue is with Spring Batch, which is using the `Chunk` itself as a key in the HashMap-based retry context cache [here](https://github.com/spring-projects/spring-batch/blob/d444a8abaff05d74c2ad895683e90f8fe5109d38/spring-batch-core/src/main/java/org/springframework/batch/core/step/item/FaultTolerantChunkProcessor.java#L436). This is different from another code path where items themselves are used as keys in the context [here](https://github.com/spring-projects/spring-batch/blob/d444a8abaff05d74c2ad895683e90f8fe5109d38/spring-batch-core/src/main/java/org/springframework/batch/core/step/item/FaultTolerantChunkProcessor.java#L404).

So we are in a case where the `Chunk` is used as a key of the HashMap of the retry context, and which is changing on retry attempts (debugging the case shows that the chunk is shrinking one item at a time when scanning is performed). Therefore, the hash code is changing on each attempt which leads to the error.

The correct way to fix this issue is by using items in the retry context, not the `Chunk` itself. This makes all the tests of `FaultTolerantChunkProcessorTests` pass without any modification, but unfortunately makes some other tests to fail.

At first, I thought this is related to the item [buffering feature](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/step/item/FaultTolerantChunkProcessor.html#setBuffering(boolean)), but it is not (the test in question is still failing with or without buffering after adding equals/hashcode to `Chunk`). So I believe this is an old hidden bug that is now popping up after adding equals and hashcode to the `Chunk` class. For that reason, I created #4370 to dig further and fix the issue correctly.

For your PR, I took the commit that adds equals/hashcode, but I omitted the commit that changes the test (because the test is correct as explained previously).

Thank you for your contribution!

**Comment by fmbenhassine** [comment]
Rebased and merged as 30e8766faa0d8946c7b0b1dda00663600f1fd537.

**Pull request closed without merging**
