### PR TITLE
Let fluent setters of SimpleStepBuilder return proper type

### LINKED ISSUE #773: ItemReadListener not being correctly registered after adding a StepExecutionListener [BATCH-2841]
**[Benne Otten](https://jira.spring.io/secure/ViewProfile.jspa?name=bolemeus)** opened **[BATCH-2841](https://jira.spring.io/browse/BATCH-2841?redirect=false)** and commented

I've stumbled upon this bug and it gave me quite a headache.
Consider the following Step configuration

```java
@Bean
public Step step1() {
    return steps.get("step1")
        .<SomeDto, SomeDto>chunk(10)
        .reader(reader())
        .processor(processor())
        .writer(writer())
        .listener(stepExecutionListener())
        .listener(itemReadListener())
        .build();
}
```

I would expect the last listener to register the ItemListener correctly, using the listener(ItemReadLiistener listener) method in the SimpleStepBuilder class, but the listener(Object listener) method in the AbstractTaskletStepBuilder gets invoked instead.

The reason for this is that the listener(StepExecutionListener listener) method resides in the StepBuilderHelper class, and that method returns an AbstractTaskletStepBuilder, and not a SimpleStepBuilder, what it should really return. In other words, the inheritance of SimpleStepBuilder > AbstractTaskletStepBuilder > StepBuilderHelper is messed up.

To illustrate, consider the following tweaked example...

```java
@Bean
public Step step1() {
    return steps.get("step1")
        .<SomeDto, SomeDto>chunk(10)
        .reader(reader())
        .processor(processor())
        .writer(writer())
        .listener(stepExecutionListener())
        .listener(itemReadListener())
        .listener(itemReadListener())
        .build();
}
```

Here, the first listener(itemReadListener) gets invoked in the AbstractTaskletStepBuilder class (which does nothing for an ItemReadListener) and the second listener(itemReadListener) gets invoked in the SimpleStepBuilder class (as it should).

---
No further details from [BATCH-2841](https://jira.spring.io/browse/BATCH-2841?redirect=false)

### PR DESCRIPTION
**Pull request by hpoettker**
Let fluent setters of `SimpleStepBuilder` return `this` with type `SimpleStepBuilder`. This makes the required order of some fluent setters a bit more lenient and prevents that `AbstractTaskletStepBuilder::listener` for parameters of type `Object` is invoked although an overloaded method specific for `SimpleStepBuilder` is intended.

Fixes #773 and #1098.

### CODE REVIEW

**Comment by hpoettker** [comment]
I rebased the original commit on the current main branch.

I also added a commit that is functionally the same but uses less unchecked casts. It's a bit cleaner but also a bit noisier as it touches more classes.

**Comment by SebastianGoeb** [comment]
Is this PR still active? I've also encountered the listener issue #773 , and would love to see this change merged.

**Comment by hpoettker** [comment]
From my side, I'd definitely consider this PR active. If it needs work, I'll be happy to do it.

The `listener` method on the DSL can be confusing. And I think this PR would really help in this regard.

**Comment by hpoettker** [comment]
I fixed the merge conflict that arised mainly from #4118 for the main branch.

There are now at least three open issues that are addressed by this PR: #773, #1098, and #3686. And I'd also consider it as having votes from the community.

It would be great to have a target release assigned to this.

**Comment by fmbenhassine** [comment]
Rebased, squashed and merged as d280556d0202124df6c8f4a8fcbddee2b123dd73. Thank you for your contribution!

**Pull request closed without merging**
