### PR TITLE
Change start-limit to match example

### PR DESCRIPTION
**Pull request by quaff**
playerSummarization is not started in Run 3.

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Can you please rebase your PR and resolve conflicts?
Many thanks upfront.

Kr,
Mahmoud

**Comment by quaff** [comment]
Please revisit it.

**Comment by mminella** [comment]
Unfortunately merging master onto your PR doesn't help.  We need you to remove the merge commit and rebase your original commit onto master.  You can read about the rebasing process in our contributor's guide here: https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#keeping-your-local-code-in-sync

**Comment by benas** [comment]
> We need you to remove the merge commit and rebase your original commit onto master

I removed the merge commit and rebased the PR on the latest master as fd2cfa356c836672e0c49c45952e63b5318b94ac.

@quaff Thank you for your contribution!

**Pull request closed without merging**
