### PR TITLE
String array command with SystemCommandTasklet

### PR DESCRIPTION
**Pull request by philippe-tr**
Thank you for taking time to contribute this pull request!
You might have already read the [contributor guide][1], but as a reminder, please make sure to:

* Sign the [contributor license agreement](https://cla.pivotal.io/sign/spring)
* Rebase your changes on the latest `master` branch and squash your commits
* Add/Update unit tests as needed
* Run a build and make sure all tests pass prior to submission

For more details, please check the [contributor guide][1].
Thank you upfront!

[1]: https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by benas** [comment]
@philippe-tr Thank you for your PR! Could you please rebase it on the latest `main` branch? It would be easier for us to only review the changes related to the PR. Thank you upfront.

**Comment by philippe-tr** [comment]
PR updated to latest main.

**Comment by philippe-tr** [comment]
Hi. Will this make into 4.2.8 or 4.3.4, or 5.0.0?

**Comment by benas** [comment]
This is better merged in v5 along with #3972.

As a side note, it seems that you did a merge and not a rebase. I will try to take care of this when tackling this PR.

**Comment by philippe-tr** [comment]
@benas Thanks for handling for correcting my merge to a rebase. I got tripped up with the upstream, forked, and local repos. I'll be more careful next time.

**Comment by fmbenhassine** [comment]
Rebased, squashed and merged as 746c9193725806a2194042a7e5be063dceca5e1a. The feature of passing a single String for the command and its arguments turned out to be confusing, so it was not merged. The way to specify the command and its arguments is through an array of Strings (similar to the `ProcessBuilder` API), which is less confusing and makes the implementation simpler (see refinement in 26c39cbbae55cbc0b7b0b61bea4091f26dc19666).

Thank you for your contribution!

**Pull request closed without merging**
