### PR TITLE
Fix for Batch 2364

### PR DESCRIPTION
**Pull request by arindamray1982**
Fix for JSR-352 partitioning restarts incorrect partitions

### CODE REVIEW

**Comment by mminella** [comment]
Can you please rebase and squash your commits?

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=408) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=408)!

**Comment by arindamray1982** [comment]
@mminella  I am new to GitHub. Can you please guide me for "rebase and squash my commits"?

**Comment by benas** [comment]
Hi @arindamray1982 ,

The ["Squash commits"](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#squash-commits) section of the contributor guide might help you. You can find an example of how to do it in the "Pro Git" book [here](https://book.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing).

Hope this helps.
Mahmoud

**Comment by arindamray1982** [comment]
Has these changes merged?

**Comment by benas** [comment]
No, otherwise we would have closed this PR. Can you please add a test that fails with the current master and passes with this PR?

As mentioned previously, please squash your commits and rebase your PR on the latest master. Thank you upfront.

**Comment by arindamray1982** [comment]
I am not able to squash the commits. Followed these:

git rebase --interactive

and then:

pick c32f6ef Change 1
squash d71e0db Change 2
squash 31f0f5a Change 3
squash d2cb5a1 Change 4
squash 4a39e38 Change 5

**Comment by benas** [comment]
ok no problem, I can take care of that. If it easier for your to create a new PR instead of rebasing/squashing etc, please go ahead, it's fine by me as well.

That said, could you please add a test to cover the case addressed here? We need to confirm the issue with a failing test and make sure this PR fixes it.

Thank you.

**Comment by arindamray1982** [comment]
@benas Thank you. I'll add one test and let you know.

I am facing the same issue with other pull request https://github.com/spring-projects/spring-batch/pull/409 created from same fork. Can you please take care of that?

**Comment by arindamray1982** [comment]
@benas Rebased with current upstream/master but unable to squash the commits. Can you please take care of that?

**Comment by benas** [comment]
Thanks, but I still don't see the test added to this PR: https://github.com/spring-projects/spring-batch/pull/408/files.

This is getting more complicated than it should be for a single file change, so I'm closing it for now. Please open a new PR by adding the changes in both production and test code as mentioned in the [contributor guide](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#submit-junit-test-cases-for-all-behavior-changes).

**Comment by arindamray1982** [comment]
@benas Thanks. Will do so.

**Comment by arindamray1982** [comment]
@benas the method I have made changes in a private method. Do you really need test cases for that?

**Comment by benas** [comment]
Updating a private method does not necessarily mean the public behaviour of the class is not impacted. You need to make sure there are no regressions and at least update the tests of the class you have changed =, `JsrPartitionHandlerTests` in this case. When I apply your changes, there are two tests failing: 

```
1. org.springframework.batch.core.jsr.partition.JsrPartitionHandlerTests#testRestartOverride`
2. org.springframework.batch.core.jsr.partition.JsrPartitionHandlerTests#testMapperWithProperties.
```

So please run a build and [make sure all tests pass](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#run-all-tests-prior-to-submission) before submitting your PR.

**Pull request closed without merging**
