### PR TITLE
Updated MySQL DDL and Added Migration Script for v4.3

### PR DESCRIPTION
**Pull request by parikshitdutta**
1. Precision added in DATE_VAL column of BATCH_JOB_EXECUTION_PARAMS in MySQL DDL
2. Respective migration script added for v4.3

As discussed, proper test case to cover the scenario to be done prior closing the PR.

Partially Fixes BATCH-2202

### CODE REVIEW

**Comment by benas** [comment]
LGTM, rebased and merged as 320cce6446736258a0b6f130ff7b303db43d6ace. As discussed, I added a test based on docker + testcontainers here 71afbbd7c7b566325bc35f63579f7d08d64f8deb.

@parikshitdutta Thank you for your contribution!

**Comment by quaff** [comment]
It's incomplete, you forgot  `LAST_UPDATED` `CREATE_TIME` `START_TIME` `END_TIME`.

**Comment by benas** [comment]
@quaff No, in the scope of this issue, the fix is complete. Those columns are in different tables which are not related to this issue. I tend to avoid including unrelated changes in a single commit.

But for consistency, we can indeed update those columns as well in all other tables to include the millisecond precision. Contributions are welcome!

**Comment by quaff** [comment]
@benas OK, I will create a PR soon.

**Pull request closed without merging**
