### PR TITLE
BATCH-2711: Fix JobParameterBuilder not to overwrite new parameters with old ones

### PR DESCRIPTION
**Pull request by peterminhk**
In a previous commit, when rerun a previously failed job with
new parameters they are replaced with previous ones.
It is somewhat critical because once failed, there is no way to run a job changing its parameter(s), unless change the status of the job manually from DB.
This problem has happened since commit
b2f8f7f9cd6605e26612773479356cbec98db3e3.

So this commit fix the issue and, also keep the purpose of previous
commit providing public method to add JobParameters to the builder.

related JiRA ticket: https://jira.spring.io/browse/BATCH-2711

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@peterminhk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=630)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=630) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@peterminhk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=630)!

**Comment by Ankitg44** [comment]
Once this PR is merger, which version of Spring Batch core have these changes??

**Comment by peterminhk** [comment]
@Ankitg44 
Since it looks critical I think it should be merged in 4.0.2 and should be released as soon as possible. But the people in Spring organization will make a decision even whether merge or not.

@mminella 
Could you give the answer?

**Comment by Ankitg44** [comment]
@peterminhk 
Thanks for quick response. 
I do agree this is critical because even for last successful job execution of a Batch job it is replacing,  new instance Job parameters with older job execution job parameters.

**Comment by benas** [comment]
Hi,

This issue is planned to be fixed in 4.0.2 and 4.1.0.RELEASE.

Kr,
Mahmoud

**Comment by aritzbastida** [comment]
Please, before releasing this PR, take a look at my comments in this JIRA issue: https://jira.spring.io/browse/BATCH-2711

All in all, I think that the PR does not completely solve the problem, because it fails to implement some use cases. I argued it with full details in the issue above.

**Comment by benas** [comment]
@aritzbastida ok thank you for all the details! I will take a look before merging the PR.

**Comment by aritzbastida** [comment]
Thanks! Keep me posted!

**Comment by benas** [comment]
Hi,

As said in JIRA, the method `addJobParametersIfAbsent` is used in `getNextJobParameters` so it is supposed to be used in a "start next instance scenario" (equivalent to `CommandLineJobRunner` with `-next` option). This method is not correct because it says in the Javadoc: `If the map previously contained a mapping for the key, the new value is ignored.` while the new value should override the existing one to be consistent with `CommandLineJobRunner` which says in the javadoc: `If the -next option is used the parameters on the command line (if any) are appended to those retrieved from the incrementer, overriding any with the same key.`

For this reason, I'm closing this PR.

Thank you @peterminhk for your contribution anyway!

Br,
Mahmoud

**Pull request closed without merging**
