### PR TITLE
First draft of a new topic about Spring Boot and Spring Batch

### PR DESCRIPTION
**Pull request by Buzzardo**
With information that I've gotten from Michael, I've built a new topic to steer readers around the worst pitfalls that come with using Spring Batch inside of a Spring Boot application.

I expect a few rounds of modifications, so please hold off on merging this commit.

### CODE REVIEW

**Comment by benas** [comment]
I was reading the spring boot reference documentation and noticed that there are different sections that show the integration with other projects: [Spring Integration](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-integration), [Spring Session](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-session), etc.

So I think this PR is better suited to be part of boot's documentation. What do you think?

**Comment by Buzzardo** [comment]
The idea is to help Batch users avoid a problem. Because the audience is Batch users, it makes more sense for this topic to be in the Batch guide.

**Comment by benas** [comment]
> Because the audience is Batch users,

For me the audience is rather Boot users, according to the title of the section `Using Spring Batch with Spring Boot`. Not all batch users are boot users. I remember giving a talk a few months ago and 80% of the audience was non-boot users (probably because for many enterprises old batch jobs (at least those older than boot) are less likely to be changed or modernized to boot once they work well in production).

> The idea is to help Batch users avoid a problem

I don't see those as problems, they are boot specific details (how boot passes parameters, how boot auto-configures a datasource, etc) that a boot user should be aware of when developing a Spring Batch job. So IMO those should go in a "Spring Batch" section in boot docs (like sections for other projects mentioned above).

**Comment by Buzzardo** [comment]
I recall that @mminella requested this addition, so I guess you should take it up with him. Perhaps things have changed in the intervening 14 months.

**Comment by snicoll** [comment]
FTR, I'd welcome a better coverage of Spring Batch in the Spring Boot reference guide. Spring Boot users are likely to look there first, especially given the nature of the document in this PR.

**Comment by benas** [comment]
I agree with @snicoll.

@Buzzardo please open this PR against boot's docs. I can help reviewing it if necessary.

**Pull request closed without merging**
