### PR TITLE
Explicitly considering Start Time not being null for running Job Executions

### PR DESCRIPTION
**Pull request by dimitrisli**
This is to exclude from capturing erroneous Job Executions. An example is
whenever a TaskRejectedException is thrown after submitting to the
taskExecutor in SimpleJobLauncher#run(), the JobExecution is left without
a Start or End Time. Also related tests are fixed.

Resolves BATCH-2675

### CODE REVIEW

**Comment by dimitrisli** [comment]
This PR is back-porting to the **3.0.x branch** the now merged to master commit: https://github.com/spring-projects/spring-batch/commit/f8f8a02a4d0ea111b638f9d48f3b3fae84fee200 from my previous PR: https://github.com/spring-projects/spring-batch/pull/663

The purpose is to also include this bugfix for legacy applications in the upcoming **3.0.10.RELEASE** aside from **4.1.0.RELEASE** and the also back-ported **4.0.x** (https://github.com/spring-projects/spring-batch/commit/13ca0e0089e88bb460754192c4295080a4c4cb54) versions.

Special attention has been given to all the elements in the vicinity of the now merged to master commit https://github.com/spring-projects/spring-batch/commit/f8f8a02a4d0ea111b638f9d48f3b3fae84fee200 that are not present in this **3.0.x** branch. The diff between this PR's commit and the above commit should be identical with the exception of the  change in the **SimpleJobRepositoryTests** class where the method doesn't exist in the **3.0.x** branch (10 files in total changed as opposed to 11 in the master merged commit).

**Comment by benas** [comment]
That's perfect! Thank you for back porting the fix to 3.0.x 👍  We will consider merging this PR when we release 3.0.10. Keep tuned.

**Comment by benas** [comment]
I'm working on this PR right now, but having a problem building the `3.0.x` branch:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':spring-batch-infrastructure:compileClasspath'.
> Could not find neo4j-cypher-dsl.jar (org.neo4j:neo4j-cypher-dsl:2.0.1).
  Searched in the following locations:
      https://repo.spring.io/libs-milestone/org/neo4j/neo4j-cypher-dsl/2.0.1/neo4j-cypher-dsl-2.0.1.jar
```

This issue is *not* related to the changes in this PR. I just wanted to give this as an FYI.

**Comment by benas** [comment]
This PR looks good to me. Rebased, squashed and merged as b28238e4b5e8633430f9a8c5f0579fa9f9d132ae.

Thank you very much @dimitrisli for back porting the fix to the `3.0.x` line!

As a side note, I fixed the build issue with 2876930ebc9b85115a4e8d108293db5181a1f9b3.

**Pull request closed without merging**
