### PR TITLE
BATCH-2761: Varargs in reader, processor, and writer builders

### PR DESCRIPTION
**Pull request by drumonii**
Adds another `delegates` builder method in `CompositeItemWriterBuilder` that takes a varargs of `ItemProcessors`

### CODE REVIEW

**Comment by drumonii** [comment]
Sounds good! I can make those changes to the other builders. But how would you like to proceed with this PR? Should I update the `BATCH-2761` to include the other builders. Or should I create new issues for each proposed builder change? Or other idea?

**Comment by mminella** [comment]
I'm hoping that the changes to the other builders won't be too much so feel free just to add them to this PR.

**Comment by benas** [comment]
Does it make sense to do the same for `org.springframework.batch.item.support.CompositeItemStream#setStreams` and `org.springframework.batch.core.listener.CompositeChunkListener#setListeners` (and may be other places where we register a list of components) ?

**Comment by drumonii** [comment]
Adjusted the PR to include changes to other builders where applicable and updated the jira issue. 

However, there was one builder where I was unable to make a varargs builder method:

```
public RepositoryItemReaderBuilder<T> arguments(List<?> arguments)
```

Since it's a `List` of `<?>`, can't do:

```
public RepositoryItemReaderBuilder<T> arguments(?... arguments)
```

Would have to be:

```
public RepositoryItemReaderBuilder<T> arguments(Object... arguments)
```

@benas I've limited this PR to builders only. I can adjust those other classes (and more) in another PR.

**Comment by benas** [comment]
> I've limited this PR to builders only

ok that's fine. However, I see that some builders have not been addressed. The following methods can also be updated to accepts varargs:

* `org.springframework.batch.item.database.builder.JdbcCursorItemReaderBuilder#queryArguments(java.lang.Object[])`
* `org.springframework.batch.item.file.builder.FlatFileItemReaderBuilder.FixedLengthBuilder#columns`
* `org.springframework.batch.item.file.builder.FlatFileItemReaderBuilder.DelimitedBuilder#includedFields`
* `org.springframework.batch.item.file.builder.FlatFileItemReaderBuilder.DelimitedBuilder#names`
* `org.springframework.batch.item.file.builder.FlatFileItemReaderBuilder.FixedLengthBuilder#names`
* `org.springframework.batch.item.file.builder.FlatFileItemWriterBuilder.FormattedBuilder#names`
* `org.springframework.batch.item.file.builder.FlatFileItemWriterBuilder.DelimitedBuilder#names`

When you change those methods to accept varargs, please update the tests accordingly, like for example in `org.springframework.batch.item.file.builder.FlatFileItemReaderBuilderTests#testSimpleFixedLength`:

```diff
- .names(new String[] {"first", "second", "third"})
+ .names("first", "second", "third")
```

Other places in the corresponding tests can be updated in the same way so it would be great to have them updated in this same PR.

In regards to the `RepositoryItemReaderBuilder`, you can add the following method:

```java
public RepositoryItemReaderBuilder<T> arguments(Object... arguments) {
     return arguments(Arrays.asList(arguments));
}
```

That's fine since we do almost the same in `org.springframework.batch.item.data.builder.MongoItemReaderBuilder#parameterValues(java.util.List<java.lang.Object>)` (for which you have already added a method with varargs of type `Object` in this PR). So that would be ok.

> I can adjust those other classes (and more) in another PR.

You are welcome. It will be great for consistency across the code base. Many thanks upfront!

And just a small reminder, please update the year in license headers and add your name with the `@author` tag in the changed files.

**Comment by drumonii** [comment]
@benas thanks for outlining what needs to be done. Very helpful. I think I've covered everything you have mentioned and ready for another review!

**Comment by benas** [comment]
Hi @drumonii ,

Thank you for all these updates! LGTM now, rebased and merged as 2f0c2a6772bbd804e793d120bd8840a2e19b5d6a.

I noticed that we missed `FlatFileItemReaderBuilder.DelimitedBuilder#includedFields(Integer[] fields)` that can also accept varargs, as well as a couple of test methods where arguments can be passed as varargs, I fixed those in e5ac0e99756c9501ce8e4c045b3edd0a7dc233fa.

Br,
Mahmoud

**Pull request closed without merging**
