### PR TITLE
Fix Java configuration example autowiring in docs

### PR DESCRIPTION
**Pull request by lkrnac**

### CODE REVIEW

**Comment by lkrnac** [comment]
Signed Individual Contributor Agreement

**Comment by mminella** [comment]
Updated the spelling error but will leave the other config difference (no need for `@Qualifier`).  Thanks for pointing this out!

**Comment by lkrnac** [comment]
There are used `step1()` and `step2()` without parameters, but that class contains only methods with parameters:

    @Bean
    protected Step step1(ItemReader<Person> reader, ItemProcessor<Person, Person> processor, ItemWriter<Person> writer) {
        return steps.get("step1")
            .<Person, Person> chunk(10)
            .reader(reader)
            .processor(processor)
            .writer(writer)
            .build();
    }

    @Bean
    protected Step step2(Tasklet tasklet) {
        return steps.get("step2")
            .tasklet(tasklet)
            .build();
    }

Are these methods defined elsewhere?

**Comment by mminella** [comment]
You're right.  This has been updated.  Thanks!

**Pull request closed without merging**
