### PR TITLE
Batch 2399 - JSON ItemReader

### PR DESCRIPTION
**Pull request by mouyang**
Overview
* more direct support for JSON
* added Unmarshaller interface for JSON similar to what is there for XML.  used Jackson as initial implementation.
* used JSR-353 to grab items one at a time and pass it off to Unmarshaller
* Handles reading from an array starting from a particular key name, or when the input is entirely an array (similar to StaxEventItemReader)

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by mminella** [comment]
I'm closing this because this really should go in the extensions repository.  Can you please move this PR to [Spring Batch Extensions](https://github.com/spring-projects/spring-batch-extensions)?

**Comment by mouyang** [comment]
No problem.  For future reference, what is the distinction for putting things in the core project or the extensions project?  I initially put it in the core project because there were other FileReaders in there.

**Comment by mann-ed** [comment]
I checked the Spring Batch Extensions and did not see a pull request or feature for JSON Item reader in it. 
@mouyang would you be willing to work on this again? I have forked your project and also spring batch extensions. I am willing to do what is needed to get this moving. I need jsonItemReader for a project i am working on. 

@mminella is Spring Batch Extensions still the correct place for this?

**Comment by mouyang** [comment]
@mann-ed feel free to work on it if you need to get it moving.  I haven't looked at it in a few years, and I can't guarantee I'll get a chance to work on it any time soon.  If you want, I can be an unofficial review for your work.  Regarding what is the correct place for this code, I would get clarification from @mminella as to why; as per my previous comment I never received an reason for it.

**Pull request closed without merging**
