### PR TITLE
3.0.x

### PR DESCRIPTION
**Pull request by wbsouza**
As mminella suggested I asked for a new feature on [ Spring Batch Jira ](https://jira.spring.io/browse/BATCH-2521).

I also have created a simple implementation to solve the problem[ Using Spring Batch JdbcCursorItemReader with NamedParameters](http://stackoverflow.com/questions/23222353/using-spring-batch-jdbccursoritemreader-with-namedparameters/38644424#38644424). 

Please, take a look and see if it's could be in some way useful to implement this feature.

Thanks,

Wellington

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wbsouza Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=427)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=427) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mminella** [comment]
I'm not sure what this PR is intended to do (I don't even see your commit in it).  Please rebase your branch and provide a pull request off a feature branch with a single commit.  Thanks!

**Comment by pivotal-issuemaster** [comment]
@wbsouza Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=427)!

**Comment by mminella** [comment]
Closing issue.  @wbsouza can open a new one with a single commit as previously mentioned.

**Pull request closed without merging**
