### PR TITLE
[BATCH-2742] AbstractPaginatedDataItemReader - save jump state

### PR DESCRIPTION
**Pull request by fawzi1414**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@fawzi1414 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=628)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=628) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fawzi1414 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=628)!

**Comment by benas** [comment]
Hi @fawzi1414 ,

Thank you for this PR! Can you please add a test that fails with the current `master` (to confirm the issue) and passes with this PR (to validate the fix)?

Thank you upfront.

Kr,
Mahmoud

**Comment by benas** [comment]
I'm closing this PR for now. Please provide a test that fails with the current master (to confirm the issue) and passes with this PR (to validate the fix) and we can re-open it.

Thank you upfront.

**Pull request closed without merging**
