### PR TITLE
Batch-3745

### PR DESCRIPTION
**Pull request by nfjcore**
bug fix for Batch-3745. 

Method ``public void write(String str, int off, int len)`` of ``org.springframework.batch.support.transaction.TransactionAwareBufferedWriter`` now calls ``StringBuilder.append(CharSequence, int, int)`` correct when off > len.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nfjcore Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3843)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3843) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nfjcore Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3843)!

**Comment by timtebeek** [comment]
Fixes https://github.com/spring-projects/spring-batch/issues/3745

**Comment by ChristophKreibich** [comment]
I had an issue with an IndexOutOfBounds error while marshalling xml as describe here: https://stackoverflow.com/questions/66476051/jaxb2marshaller-problem-with-string-that-contains

I downloaded the source for 4.3.x, added the patch from this pull request, build and tested successfully with my application. This pull request is solving the issue.

**Comment by benas** [comment]
LGTM. Rebased and merged as 63b6dea51489082b205a20d2d83c1df2383faa75. Thank you for your contribution!

**Pull request closed without merging**
