### PR TITLE
 Replace explicit type with diamond operator in core module

### PR DESCRIPTION
**Pull request by drumonii**

### CODE REVIEW

**Comment by mminella** [comment]
Since you already have these as one commit per module, can you please break them up into one PR per module so that it is easier for us to review?

**Comment by drumonii** [comment]
Yes! No problem!

**Comment by drumonii** [comment]
@mminella Done!

**Comment by benas** [comment]
LGTM. Rebased and merged as 4192bfe01ede032057867ca13aac03563371fbb1.

@drumonii Thank you for doing this! For next PRs, please don't forget to update the date in license headers and add your name as an author in the files you modify.

**Pull request closed without merging**
