### PR TITLE
BATCH-2647 JobStep does not update the ExitStatus of the StepExecution

### PR DESCRIPTION
**Pull request by eduardojolo**
As said in the AbstractStep: "Subclasses should set the {@link ExitStatus} on the {@link StepExecution} before returning."
Relevant for a JobExecution custom exit status.

### CODE REVIEW

**Comment by mminella** [comment]
Can we get a unit test around this?

**Comment by eduardojolo** [comment]
Sure, I will implement it and update the pull request.

**Comment by eduardojolo** [comment]
I have implemented a simple test that covers the change. Please, let me know if you think anything other than that is needed.

**Comment by mminella** [comment]
LGTM.  Squashed, rebased, and merged as 509be945fcb1761d46e0fb07b30afefedac64d27.  Thanks for the contribution!

**Pull request closed without merging**
