### PR TITLE
Update step.adoc

### PR DESCRIPTION
**Pull request by wavoe**
typo in a variable

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wavoe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3630)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3630) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by benas** [comment]
@wavoe Thanks for the PR! LGTM.

Could you please sign the Contributor License Agreement?

**Comment by pivotal-issuemaster** [comment]
@wavoe Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=3630)!

**Comment by benas** [comment]
Merged. Thank your for your contribution!

**Pull request merged**
