### PR TITLE
Remove call to String.toCharArray

### PR DESCRIPTION
**Pull request by obourgain**
Trivial PR to remove a lot of char[] allocations

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Can you please rebase your PR and resolve conflicts?
Many thanks upfront.

Kr,
Mahmoud

**Comment by obourgain** [comment]
Hi, I rebased the PR

**Comment by obourgain** [comment]
Hello, any news on this ?

**Comment by benas** [comment]
@obourgain Thank you for your PR! LGTM. Rebased and merged as 2ee15d2f4cf4af1d43dad5353fb58f92b8893a83.

**Pull request closed without merging**
