### PR TITLE
Fix for Batch 2488

### PR DESCRIPTION
**Pull request by arindamray1982**
Fix for JSR-352 Property Substitutions expression with default value doesn't work as expected

### CODE REVIEW

**Comment by mminella** [comment]
This PR doesn't pass all the tests.  Specifically `JobPropertySubstitutionTests#testPropertySubstitutionSimple` fails.  Please update the PR so that it passes all tests and squash your commits.

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=410) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@arindamray1982 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=410)!

**Comment by benas** [comment]
I'm closing this PR for now. As mentioned by Michael, the `JobPropertySubstitutionTests#testPropertySubstitutionSimple` is failing. Please make sure all tests pass (as noted in the [contributor guide](https://github.com/spring-projects/spring-batch/blob/master/CONTRIBUTING.md#run-all-tests-prior-to-submission)) and we can re-open this PR.

Thank you upfront.

**Pull request closed without merging**
