### PR TITLE
remove dead code related to PagingQueryProvider#generateJumpToItemQuery

### PR DESCRIPTION
**Pull request by jpraet**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jpraet Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-batch&pullRequestId=422) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jpraet Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-batch&pullRequestId=422)!

**Comment by hpoettker** [comment]
I think this PR has a lot of merit and it's great that the PR is assigned to the release of Spring Batch 5. The presumeably dead code may not affect users but it does lead to unnecessary work when doing maintenance as e.g. in #4047.

The PR is somewhat out of date and needs some work. Is there interest in a fresh PR with the same goal?

**Comment by fmbenhassine** [comment]
Yes, I think v5 is a good opportunity to merge this. The PR was based on v3 indeed, so it would be great if it's rebased on the latest `main`.

> Is there interest in a fresh PR with the same goal?

Sure! However, to be fair, I would first ask the original author of the PR if he is willing to update it for v5 (the GA is currently planned for around mid-November 2022), otherwise you can open a fresh PR with the same goal.

@jpraet wdyt?

**Comment by fmbenhassine** [comment]
Closing this, superseded by https://github.com/spring-projects/spring-batch/pull/4207. Thanks to the original author anyway!

**Pull request closed without merging**
